FROM maven:3-eclipse-temurin-21 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM  eclipse-temurin-21-alpine
COPY --from=build /target/merchandiseMgmtERP.jar merchandiseMgmtERP.jar

EXPOSE 8089
ENTRYPOINT ["java","-jar","merchandiseMgmtERP.jar"]