# Stage 1: Build the application
FROM maven:3-eclipse-temurin-21 AS build

WORKDIR /app

# Copy necessary files for dependency caching
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy the complete source code
COPY src ./src

# Package the application (skip tests for faster build)
RUN mvn clean package -DskipTests

# Stage 2: Create the runtime image
FROM eclipse-temurin:21-alpine

WORKDIR /merchandiseMgmtERP

# Copy the built JAR file
COPY --from=build /merchandiseMgmtERP/target/merchandiseMgmtERP-0.0.1-SNAPSHOT.jar merchandiseMgmtERP.jar

# Expose the application port
EXPOSE 8080

# Set the entry point for the application
ENTRYPOINT ["java", "-jar", "merchandiseMgmtERP.jar"]





#FROM maven:3-eclipse-temurin-21 AS build
#COPY . .
#RUN mvn clean package -DskipTests
#
#FROM  eclipse-temurin:21-alpine
#COPY --from=build /target/merchandiseMgmtERP-0.0.1-SNAPSHOT.jar merchandiseMgmtERP.jar
#
#EXPOSE 8089
#ENTRYPOINT ["java","-jar","merchandiseMgmtERP.jar"]